name: Run Tests

on:
  pull_request:
    branches: "**"

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.1', '3.2']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rspec --profile 10 --format RspecJunitFormatter --out test_results/rspec.xml --format progress
    - name: Upload result
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: rspec-${{ matrix.ruby-version }}.xml
        path: test_results/rspec.xml
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Rspec Tests - ${{ matrix.ruby-version }}
        path: test_results/rspec.xml
        reporter: java-junit
